services:
  db:
    image: postgres:16
    container_name: annuel-prod-postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./backend/docker_data/prod/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: scripts/dockerfile/prod.dockerfile
    container_name: annuel-prod-backend
    restart: always
    env_file:
      - .env.prod.local
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - backend_uploads:/app/uploads
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: scripts/dockerfile/prod.dockerfile
    container_name: annuel-prod-frontend
    restart: always
    env_file:
      - .env.prod.local
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT}:3000"
    networks:
      - app_network

  umami-db:
    image: postgres:16
    container_name: annuel-prod-umami-postgres
    restart: always
    environment:
      POSTGRES_DB: ${UMAMI_DB_NAME}
      POSTGRES_USER: ${UMAMI_DB_USER}
      POSTGRES_PASSWORD: ${UMAMI_DB_PASSWORD}
    volumes:
      - ./backend/docker_data/prod/umami_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - app_network

  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    container_name: annuel-prod-umami
    restart: always
    depends_on:
      umami-db:
        condition: service_healthy
    ports:
      - "${UMAMI_PORT}:3000"
    environment:
      DATABASE_URL: postgresql://${UMAMI_DB_USER}:${UMAMI_DB_PASSWORD}@umami-db:5432/${UMAMI_DB_NAME}
      DATABASE_TYPE: postgresql
      APP_SECRET: ${UMAMI_APP_SECRET}
      HASH_SALT: ${UMAMI_HASH_SALT}
    networks:
      - app_network

networks:
  app_network:

volumes:
  backend_uploads:
